artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/krishanwalia30/UsefulDatasets/raw/main/titanic_dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  
data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ['Titanic-Dataset.csv']

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/transformed_data.csv

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/transformed_data.csv
  model_path: artifacts/model_trainer
  metrics_file_name: metrics.yaml